### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by Heraclion** [raknjak/CIMembership#11]
Can you add in script to add new pages from adminpanel?and add scripts from there?

**Comment by raknjak** [comment]
_"Can you add in script to add new pages from adminpanel?"_
You mean like a CMS? I'd rather see this in a fork tbh.
Could we integrate something like https://www.cszcms.com/? Why reinvent the wheel.

_"and add scripts from there?"_
This might mean several things, what do you mean?

**Comment by raknjak** [comment]
#13

**Comment by raknjak** [comment]
**sry closed too soon this needs clarity:**
"and add scripts from there?"
This might mean several things, what do you mean?

**Comment by raknjak** [comment]
I will close this for now due to inactivity. Just add a new issue with detailed info if you have any more questions plz thx.
