### ISSUE TITLE
Twitter & Google Login Fails

### ISSUE THREAD

**Issue by arshem** [raknjak/CIMembership#16]
Setting up Twitter & Google Logins through the application seems to not work. 

Google Error:
```
Please verify the following:
Could not load userdata. 
```
Callback URL for Google is:
https://domain/site/auth/oauth2/verify/Google

Twitter Error is more lengthy:

```
An uncaught Exception was encountered

Type: League\OAuth1\Client\Credentials\CredentialsException

Message: Received HTTP status code [403] with message "Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings" when getting temporary credentials.

Filename: /home/matchfur/domain/site/application/vendor/PHPLeague-OAuth1/league/oauth1-client/src/Client/Server/Server.php

Line Number: 418

Backtrace:

File: /home/matchfur/domain/site/application/vendor/PHPLeague-OAuth1/league/oauth1-client/src/Client/Server/Server.php
Line: 93
Function: handleTemporaryCredentialsBadResponse

File: /home/matchfur/domain/site/application/modules/auth/controllers/Oauth1.php
Line: 57
Function: getTemporaryCredentials

File: /home/matchfur/domain/site/index.php
Line: 315
Function: require_once

```

Callback URL for Twitter is: 
 https://domain/site/auth/OAuth1/verify/Twitter

According to the documentation (manual) I set them up correctly.

**Comment by raknjak** [comment]
For **google**, the url should look like
https://cimembership.io/demo/auth/oauth2/verify/Google
The 403 error usually means that this url or some other setting is not correct BUT with Google it can take a while before it actually starts working. I've had people report it taking up to 12-24 hours.
Also if when called from non-secure http protocal to https it will not work either. This was reported a few times, too.

**Twitter**: I have the same issue. The solution is to capitalize the word Twitter in the callback URL.
Apparently they made it case sensitive about a month ago.
https://twittercommunity.com/t/callback-url-not-approved-but-worked-for-months/107261

**Comment by arshem** [comment]
Got twitter working now =) I had OAuth1 vs oauth1. Changed it without capitalization on oauth1 and it works =) 

I'm always using https for google and I set this up on Sunday, it's Tuesday now. I'll try it again tomorrow to see if it works.

**Comment by raknjak** [comment]
It should work though.
In application/modules/auth/controllers/OAuth2.php line 134-135 could you try to output the userdate

$user = $providerObject->getResourceOwner($token);
var_dump($user); // maybe add a die(); here

to see what happens?

**Comment by arshem** [comment]
Hey RaknJak

I did that, it didn't return any values or die, so then I attached $e (exception value) to the error message (which I think is pretty beneficial for debugging). 

Could not load userdata. exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Access Not Configured. Google+ API has not been used in project ############# before or it is disabled

Did I miss this part in the manual?

**Comment by raknjak** [comment]
So when I go into my Google developer console _dashboard_ I have Google+ API enabled, not sure whether the manual actually mentions this. The manual is out of date here and there unfortunately.

**Comment by raknjak** [comment]
If it's not enabled go to library on the left and look for it there.

**Comment by arshem** [comment]
Both are working now =) Thanks Raknjak! I'll close this out, but seriously thank you. Not having Google+ API enabled was the issue for google and twitter was case-sensitivity!
