### ISSUE TITLE
how to fix mixed content issue

### ISSUE THREAD

**Issue by kadaejung** [raknjak/CIMembership#18]
Hi Raknjak,

I tried to use http or https. 
my issue is mixed content.

Please suggest me how to fix this problem.

Thank you
Prasit

**Comment by raknjak** [comment]
Thanks for opening a ticket, can you show me the exact error please?
a trick could be to just use links like //example.com/mypage in stead of defining http or https it should then automatically pick up https.
But since https is now very necessary we should try to make everything work with that one - if you post me the error we'll get it fixed.

**Comment by kadaejung** [comment]
Hi Raknjak,

you can see at my front-end url : https://www.futbook.com/  vs  http://www.futbook.com/
please inspect in console, shown "Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS."

Thank you

**Comment by raknjak** [comment]
Here is an example of how to generate a link correctly:
`<link href="<?php echo base_url(); ?>assets/css/<?php echo Settings_model::$db_config['active_theme']; ?>/bootstrap.min.css" rel="stylesheet">`

In JS you can use the variable CONFIG.base_url

**Comment by raknjak** [comment]
API call is it a url? same method probably applies

**Comment by kadaejung** [comment]
Hi raknjak,

Please help me again, when I move to new VPS with same as last VPS, I show the same error "mix content"

What I wrong? Please suggest me
https://www.futbook.com

Thank you

**Comment by raknjak** [comment]
style sheets are not loaded over https

<link rel="shortcut icon" href="http://www.futbook.com/assets/images/soccer/favicons/favicon.ico">
--
  | <link rel="apple-touch-icon" sizes="120x120" href="http://www.futbook.com/assets/images/soccer/favicons/favicon-120.png">
  | <link rel="apple-touch-icon" sizes="152x152" href="http://www.futbook.com/assets/images/soccer/favicons/favicon-152.png">
  |  


just use the trick above everywhere


in browser us F!@ to debug errors you'll easily find them all.
