### ISSUE TITLE
problem after login

### ISSUE THREAD

**Issue by fbeke** [raknjak/CIMembership#20]
Hi folks, 
anyone experienced problem with logins? After login i have a repeated, never ending redirect between /login and /auth/login/validate pages. There are similar problems after validating new registrations.
Any ideas, what i probably messed up? The page is on https with valid ssl certificate.
Thanks!
F.

**Comment by raknjak** [comment]
Is there a cookie domain? config.php:
$config['cookie_domain']	= '.domainnmame';
$config['cookie_domain']	= 'localhost';

Maybe put a breakpoint in login controller (auth module) at line 73
var_dump($userData);die;
to see what it returns?

Same goes for core/Private_controller line 55

**Comment by fbeke** [comment]
thanks for your reply, cookie domain is set, will try the debug later
but forgot to add, that when i go to the homepage after those reloads, then i'm logged in

**Comment by raknjak** [comment]
some extra tips:
- compare to riginal code
- remove site cookies from browser and clean sessions from database
- since private_controller seems to redirect you back, output cookies there var_dump($cookie)

**Comment by raknjak** [comment]
closing this now - assumed solved, just reopen if you need any help
