### ISSUE TITLE
Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### ISSUE THREAD

**Issue by raknjak** [raknjak/CIMembership#22]
https://forum.codeigniter.com/printthread.php?tid=72393

Severity: 8192

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

Backtrace:

File: C:\xampp\htdocs\CIMembership\application\vendor\MX\Router.php
Line: 239
Function: strpos

File: C:\xampp\htdocs\CIMembership\application\vendor\MX\Router.php
Line: 72
Function: set_class

File: C:\xampp\htdocs\CIMembership\index.php
Line: 315
Function: require_once

**Comment by raknjak** [comment]
fixed with latest commit e866ee3dcc8095cb3c43f9fbe6da3c64cc0fdd4b

**Comment by ammsway** [comment]
// if (strpos($class, $suffix) === FALSE)
replay with this
if ($suffix && strpos($class, $suffix) === FALSE)

![image](https://user-images.githubusercontent.com/62007780/76290566-6dea9b00-62d1-11ea-9290-8a783da4bf0c.png)

**Comment by berkaycalti** [comment]
Thank you !

**Comment by coderHanif** [comment]
It's work! Thank you, Brother,@ammsway.
