### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by Heraclion** [raknjak/CIMembership#9]
Can you make chat rooms with delege history,manage chatrooms and rooms passworded?and alao when you enter to chat must come with a message....user has join the chat-room,smilies end bbcode,YouTube integration when you post the link....thank you

**Comment by raknjak** [comment]
I'll create a feature request for this. chat can be a lot of work (webservices?)

**Comment by raknjak** [comment]
https://github.com/raknjak/CIMembership/issues/13
